# Generated by Django 3.0.2 on 2020-04-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_auto_20200408_2000'),
        ('buying', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='items.Item'),
        ),
        migrations.DeleteModel(
            name='UserCartItem',
        ),
    ]
