# Generated by Django 3.0.4 on 2020-03-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200327_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='inventory',
            new_name='quantity',
        ),
    ]
