# Generated by Django 3.0.2 on 2020-04-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='test item', max_length=100),
        ),
    ]
