# Generated by Django 3.0.2 on 2020-04-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20200408_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategories',
            old_name='category_name',
            new_name='category',
        ),
    ]
