# Generated by Django 3.0.2 on 2020-04-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20200408_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='items.Category'),
        ),
        migrations.DeleteModel(
            name='ItemCategories',
        ),
    ]
